# SPDX-FileCopyrightText: 2025 Hüsamettin Arabacı
# SPDX-License-Identifier: MIT

extends:
  - "@commitlint/config-conventional"

rules:
  type-enum:
    - 2
    - always
    - [feat, fix, chore, refactor, test, docs, ci, perf, build, release, hotfix, style]
