version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "type:dependency"
      - "status:automated"
    assignees:
      - "husamettinarabaci"
