# SPDX-FileCopyrightText: 2025 Husamettin ARABACI
# SPDX-License-Identifier: MIT

github: hTuneSys
# open_collective: hexafn
# patreon: hexafn
# custom: ['https://hexafn.com/sponsor', 'https://buymeacoffee.com/hexafn']
