# SPDX-FileCopyrightText: 2025 Hüsamettin Arabacı
# SPDX-License-Identifier: MIT

github: husamettinarabaci
# open_collective: hexafn
# patreon: hexafn
# custom: ['https://hexafn.com/sponsor', 'https://buymeacoffee.com/hexafn']
