# SPDX-FileCopyrightText: 2025 Hüsamettin Arabacı
# SPDX-License-Identifier: MIT

[package]
name = "hexafn"
version = "0.1.0"
edition = "2024"
authors = ["hexaTune Team <info@hexafn.com>"]
description = "Modular event-driven function engine using the 6F lifecycle flow"
license = "MIT"
repository = "https://github.com/hTuneSys/hexaFn"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]