version = 1

[[annotations]]
path = ["docs/assets/**","docs/CNAME","docs/index.html"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Husamettin ARABACI"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["hexaFn.code-workspace"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Husamettin ARABACI"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["package.json","CHANGELOG.md","Cargo.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Husamettin ARABACI"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [".github/ISSUE_TEMPLATE/**",".github/PULL_REQUEST_TEMPLATE.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Husamettin ARABACI"
SPDX-License-Identifier = "MIT"
