version = 1

[[annotations]]
path = ["docs/assets/diagram.png", "docs/assets/hexaFn-logo.png", "docs/assets/favicon.ico", "docs/CNAME"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Hüsamettin Arabacı"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "package.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Hüsamettin Arabacı"
SPDX-License-Identifier = "MIT"
