---
name: "🧠 Design Proposal (RFC)"
about: "Propose a major architectural or functional change for hexaFn"
title: "[RFC] "
labels: ["type:proposal", "status:discussion"]
---

### 🧠 Problem or Motivation

Describe the need for this proposal. What problem does it solve or opportunity does it create?

---

### 🛠️ Proposed Solution

Explain the architecture, design, or approach you'd like to suggest.

---

### 🔄 Alternatives Considered

What other options did you consider or discard? Why?

---

### 📈 Impact

How will this affect current users, modules, or interfaces?

---

### 🔗 References or Related Proposals

(Optional) Link to related issues, RFCs, articles, or code examples.
