name: "🧠 Design Proposal (RFC)"
description: Propose a major architectural or modular design idea
labels: ["type:proposal", "status:discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Please use this template to share large or long-term ideas about hexaFn’s architecture or capabilities.
  - type: textarea
    id: motivation
    attributes:
      label: 🧠 Problem or Motivation
      description: What problem does this solve or what opportunity does it create?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 🛠️ Proposed Solution
      description: Describe the solution, architecture, or module you’re suggesting.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: What other options did you evaluate? Why didn’t you choose them?
  - type: textarea
    id: impact
    attributes:
      label: 📈 Impact
      description: How would this affect existing systems, users, or other modules?
  - type: textarea
    id: references
    attributes:
      label: 🔗 References
      description: (Optional) Related RFCs, issues, diagrams, or research.
