name: "🚀 Feature Idea"
description: Propose a new idea or capability
labels: ["type:feature", "status:discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for sharing your idea with the hexaFn team!
  - type: textarea
    id: idea
    attributes:
      label: 💡 What is your idea?
      description: Describe your idea or proposed enhancement.
      placeholder: I want hexaFn to support...
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: 🔍 Why do you need it?
      description: What problem does this solve or what opportunity does it create?
    validations:
      required: true
