# SPDX-FileCopyrightText: 2025 Hüsamettin Arabacı
# SPDX-License-Identifier: MIT

name: 🤖 CI

on:
  pull_request:
  push:

jobs:
  fmt:
    name: Check Formatting (hexaFn)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check code formatting
        run: cargo fmt -- --check

  clippy:
    name: Run Clippy Linter (hexaFn)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  build:
    name: Build Project (hexaFn)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --locked --all-targets

  test:
    name: Run Tests (hexaFn)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test --locked --all-targets
