name: Code Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    name: Run coverage analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run Coverage
        run: |
          mkdir -p coverage
          cargo tarpaulin --out Xml --output-dir coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: coverage/tarpaulin-report.xml
          flags: rust
          fail_ci_if_error: true
