# SPDX-FileCopyrightText: 2025 Hüsamettin Arabacı
# SPDX-License-Identifier: MIT

name: 🔖 PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label PR (hexaFn)
    runs-on: ubuntu-latest
    steps:
      - name: Run Labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Dosya adını güncelledik
          configuration-path: .github/labeler.yml
          dot: true
