# SPDX-FileCopyrightText: 2025 Hüsamettin Arabacı
# SPDX-License-Identifier: MIT

name: 🔖 PR Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    name: Label PR (hexaFn)
    runs-on: ubuntu-latest
    steps:
      - name: Run Labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: false
          dot: true