name: Check Semantic PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-title:
    name: Validate PR title (hexaFn)
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            perf
            test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
